#!/bin/bash

set -eu

BACKUP_FILE=${BACKUP_FILE:-"/backup/ckan-backup.tar"}

if [[ -z "$BACKUP_FILE" ]]; then
    echo "Error: BACKUP_FILE is not set."
    exit 1
fi

if [[ "$BACKUP_FILE" == "/backup/ckan-backup.tar" ]]; then
    echo "Removing old backup file: $BACKUP_FILE"
    rm -f "$BACKUP_FILE"
fi

TMP_FOLDER=`mktemp -d`
cd $TMP_FOLDER

# Set version
echo $CKAN_BACKUP_VERSION > ckan-backup.version

# Backup db
PGPASSWORD="$CKAN_DB_PASSWORD" pg_dump --format=custom \
    -h "$POSTGRES_HOST" -p 5432 \
    -U "$CKAN_DB_USER" -d "$CKAN_DB" -f "$BACKUP_FILE"

# TODO: Backup files